services:
  db:
    image: postgres:16
    container_name: secureauth-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./secureAuthBE
      dockerfile: Dockerfile
    container_name: secureauth-be
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SECURITY_JWT_EXPIRATION_MINUTES: ${SECURITY_JWT_EXPIRATION_MINUTES}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    security: #inserisco queste config anche qui, perch√® cosi se mi scordo di configurare la JWT mi esce subito errore all'avvio di spring
      jwt:
        secret: ${SECURITY_JWT_SECRET}
        expiration-minutes: ${SECURITY_JWT_EXPIRATION_MINUTES:15}

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./secureAuthFE
      dockerfile: Dockerfile
    container_name: secureauth-fe
    depends_on:
      - backend
    ports:
      - "3000:80"
#creo il volume in cui saranno contenuti i dati del db
volumes:
  dbdata:
