services:
  db:
    image: postgres:16
    container_name: secureauth-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./secureAuthBE
      dockerfile: Dockerfile
    container_name: secureauth-be
    depends_on:
      - db
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_EXPIRATION_MINUTES: ${SECURITY_JWT_EXPIRATION_MINUTES}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      TINK_KEYSET_B64: ${TINK_KEYSET_B64}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

  frontend:
    build:
      context: ./secureAuthFE
      dockerfile: Dockerfile
    container_name: secureauth-fe
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    container_name: secureauth-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "443:443"
    volumes:
      - ./nginx/proxy.config:/etc/nginx/conf.d/default.conf:ro
      - ./certs/localhost.pem:/etc/nginx/certs/localhost.pem:ro
      - ./certs/localhost-key.pem:/etc/nginx/certs/localhost-key.pem:ro


#creo il volume in cui saranno contenuti i dati del db
volumes:
  dbdata:
