services:
  db:
    image: postgres:16
    container_name: secureauth-db
    environment:
      POSTGRES_DB: secureauth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!?
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./secureAuthBE
      dockerfile: Dockerfile
    container_name: secureauth-be
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/secureauth
      SPRING_DATASOURCE_USERNAME: admin 
      SPRING_DATASOURCE_PASSWORD: admin123!?
      #DDL_AUTO mi permette di generare tabelle in base alle entity del backend
      #il parametro update è utile in sviluppo perchè mi permette di poter modificare sempre le tabelle, in quanto se aggiunto attributi o tuple
      #aggiorna il DB in automatico, dato che in sviluppo potrei aver bisogno di aggiungere attributi o toglierli.
      #in produzione utilizzerò Flyway/Liqibase in quanto mi permettono di mantenere un DB in maniera piu sicura con log, rollback del db, migration piu sicure ecc
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect #genero sql compatibile con postgress
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./secureAuthFE
      dockerfile: Dockerfile
    container_name: secureauth-fe
    depends_on:
      - backend
    ports:
      - "3000:80"
#creo il volume in cui saranno contenuti i dati del db
volumes:
  dbdata:
